// Canonical Overwatch names, roles, mechanics heuristics, and map modes used
// by Coach HQ, the client app, and the server-side match normalizer.
export const OVERWATCH_CATALOG = Object.freeze({
  heroes: Object.freeze([
    { name: "Ashe", role: "Damage", c: 3, t: 0, s: 1, mvt: false, aim: "Scoped flicks & static precision" },
    { name: "Bastion", role: "Damage", c: 0, t: 3, s: 1, mvt: false, aim: "Recon-mode sustained tracking" },
    { name: "Cassidy", role: "Damage", c: 2, t: 1, s: 2, mvt: false, aim: "Hitscan flicks + target switching" },
    { name: "Echo", role: "Damage", c: 1, t: 2, s: 1, mvt: true, aim: "Tracking from the air" },
    { name: "Emre", role: "Damage", c: 2, t: 1, s: 1, mvt: false, aim: "Burst hitscan precision + target switching" },
    { name: "Freja", role: "Damage", c: 2, t: 1, s: 1, mvt: true, aim: "Projectile flicks on the move" },
    { name: "Genji", role: "Damage", c: 1, t: 1, s: 1, mvt: true, aim: "Projectile + movement aim" },
    { name: "Hanzo", role: "Damage", c: 3, t: 0, s: 1, mvt: false, aim: "Projectile flick precision" },
    { name: "Junkrat", role: "Damage", c: 0, t: 0, s: 0, mvt: true, aim: "Splash/prediction, low raw aim" },
    { name: "Mei", role: "Damage", c: 1, t: 2, s: 0, mvt: false, aim: "Beam tracking + icicle flicks" },
    { name: "Pharah", role: "Damage", c: 0, t: 2, s: 0, mvt: true, aim: "Air-to-ground tracking" },
    { name: "Reaper", role: "Damage", c: 0, t: 2, s: 1, mvt: true, aim: "Close-range tracking" },
    { name: "Shion", role: "Damage", c: 1, t: 2, s: 2, mvt: true, aim: "Rapid-fire tracking + mobile target switching" },
    { name: "Sojourn", role: "Damage", c: 2, t: 2, s: 1, mvt: false, aim: "Rail charge tracking + flick" },
    { name: "Soldier: 76", role: "Damage", c: 0, t: 3, s: 1, mvt: false, aim: "Hitscan tracking" },
    { name: "Sombra", role: "Damage", c: 0, t: 2, s: 1, mvt: true, aim: "Close tracking + repositioning" },
    { name: "Symmetra", role: "Damage", c: 0, t: 2, s: 0, mvt: false, aim: "Beam tracking" },
    { name: "Torbjorn", role: "Damage", c: 1, t: 1, s: 1, mvt: false, aim: "Mixed mid-range" },
    { name: "Tracer", role: "Damage", c: 0, t: 3, s: 1, mvt: true, aim: "Reactive close tracking + strafe aim" },
    { name: "Venture", role: "Damage", c: 1, t: 1, s: 1, mvt: true, aim: "Projectile + burrow movement" },
    { name: "Widowmaker", role: "Damage", c: 3, t: 0, s: 1, mvt: false, aim: "Static flick precision" },
    { name: "D.Va", role: "Tank", c: 0, t: 2, s: 0, mvt: true, aim: "Spread tracking, flight" },
    { name: "Doomfist", role: "Tank", c: 0, t: 0, s: 0, mvt: true, aim: "Ability-based, minimal aim" },
    { name: "Hazard", role: "Tank", c: 0, t: 1, s: 0, mvt: true, aim: "Spike burst + mobility" },
    { name: "Junker Queen", role: "Tank", c: 1, t: 1, s: 1, mvt: false, aim: "Shotgun + knife mixed" },
    { name: "Mauga", role: "Tank", c: 0, t: 2, s: 0, mvt: false, aim: "Dual-minigun tracking" },
    { name: "Orisa", role: "Tank", c: 0, t: 2, s: 0, mvt: false, aim: "Sustained tracking" },
    { name: "Ramattra", role: "Tank", c: 0, t: 1, s: 0, mvt: false, aim: "Staff tracking" },
    { name: "Reinhardt", role: "Tank", c: 0, t: 0, s: 0, mvt: false, aim: "Melee, no aim" },
    { name: "Roadhog", role: "Tank", c: 2, t: 1, s: 0, mvt: false, aim: "Hook + burst flick" },
    { name: "Sigma", role: "Tank", c: 1, t: 1, s: 0, mvt: false, aim: "Projectile lobs" },
    { name: "Winston", role: "Tank", c: 0, t: 0, s: 0, mvt: true, aim: "Auto-aim, movement only" },
    { name: "Wrecking Ball", role: "Tank", c: 0, t: 0, s: 0, mvt: true, aim: "Movement, minimal aim" },
    { name: "Zarya", role: "Tank", c: 0, t: 3, s: 0, mvt: false, aim: "Beam tracking" },
    { name: "Ana", role: "Support", c: 3, t: 0, s: 1, mvt: false, aim: "Scoped precision + flicks" },
    { name: "Baptiste", role: "Support", c: 2, t: 1, s: 1, mvt: false, aim: "3-round burst placement" },
    { name: "Brigitte", role: "Support", c: 0, t: 0, s: 0, mvt: false, aim: "Melee, no aim" },
    { name: "Illari", role: "Support", c: 2, t: 1, s: 1, mvt: false, aim: "Charged rifle precision" },
    { name: "Juno", role: "Support", c: 0, t: 2, s: 0, mvt: true, aim: "Gun tracking + flight" },
    { name: "Kiriko", role: "Support", c: 3, t: 0, s: 1, mvt: true, aim: "Kunai precision + wall-climb" },
    { name: "Lifeweaver", role: "Support", c: 1, t: 1, s: 0, mvt: false, aim: "Charged thorn aim" },
    { name: "Lucio", role: "Support", c: 0, t: 1, s: 0, mvt: true, aim: "Movement, low aim" },
    { name: "Mercy", role: "Support", c: 1, t: 0, s: 0, mvt: true, aim: "Situational pistol" },
    { name: "Moira", role: "Support", c: 0, t: 1, s: 0, mvt: true, aim: "Soft-lock, low raw aim" },
    { name: "Zenyatta", role: "Support", c: 2, t: 1, s: 1, mvt: false, aim: "Orb volley precision" }
  ]),
  maps: Object.freeze([
    { name: "Antarctic Peninsula", mode: "Control" }, { name: "Busan", mode: "Control" },
    { name: "Ilios", mode: "Control" }, { name: "Lijiang Tower", mode: "Control" },
    { name: "Nepal", mode: "Control" }, { name: "Oasis", mode: "Control" }, { name: "Samoa", mode: "Control" },
    { name: "Circuit Royal", mode: "Escort" }, { name: "Dorado", mode: "Escort" },
    { name: "Havana", mode: "Escort" }, { name: "Junkertown", mode: "Escort" },
    { name: "Rialto", mode: "Escort" }, { name: "Route 66", mode: "Escort" },
    { name: "Shambali Monastery", mode: "Escort" }, { name: "Watchpoint: Gibraltar", mode: "Escort" },
    { name: "Blizzard World", mode: "Hybrid" }, { name: "Eichenwalde", mode: "Hybrid" },
    { name: "Hollywood", mode: "Hybrid" }, { name: "King's Row", mode: "Hybrid" },
    { name: "Midtown", mode: "Hybrid" }, { name: "Neon Junction", mode: "Hybrid" },
    { name: "Numbani", mode: "Hybrid" }, { name: "Paraiso", mode: "Hybrid" },
    { name: "Colosseo", mode: "Push" }, { name: "Esperanca", mode: "Push" },
    { name: "New Queen Street", mode: "Push" }, { name: "Runasapi", mode: "Push" },
    { name: "Aatlis", mode: "Flashpoint" }, { name: "New Junk City", mode: "Flashpoint" },
    { name: "Suravasa", mode: "Flashpoint" },
    { name: "Hanaoka", mode: "Clash" }, { name: "Throne of Anubis", mode: "Clash" }
  ])
});

export default OVERWATCH_CATALOG;
